spring.application.name=eventos-api
spring.datasource.url=jdbc:mysql://localhost:3306/Eventos?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

spring.jpa.show-sql=true